project:
  type: website
  output-dir: docs

website:
  favicon: img/harmonize.ico
  title: "Innovalab with IMT Cusco"
  twitter-card: 
    image: "https://raw.githubusercontent.com/healthinnovation/cusco/gh-pages/background/background.jpg"
    creator: "@antony_barja"
    site: "@antony_barja"
  open-graph:
    description: "This website showcases data visualizations on snails, water bodies, Fasciola hepatica cases,environmental indices,temperature, and other data collected in the TMRC project. The primary objective is to characterize the microenvironment of communities in Cusco using high-resolution images, including processed images from multispectral and thermal drones.These tools enable us to identify potential areas for water body formation and snail proliferation, there by contributing to the understanding and management of these phenomena in the local environmen"
    image: "https://raw.githubusercontent.com/healthinnovation/cusco/gh-pages/background/background.jpg"
  navbar:
    logo: https://epi-rgee.netlify.app/logos/logo_v2.png
    left:
      - href: index.qmd
        text: Home
      - href: webmap.qmd
        text: Webmap

    right:
      - icon: github
        href: https://github.com/healthinnovation/harmonize
      - icon: twitter
        href: https://twitter.com/innovalab_imt
  
format:
  html:
    theme: cosmo
    css: css/style.css
    toc: true

editor: visual