project:
  type: website
  output-dir: docs

website:
  favicon: img/harmonize.ico
  title: "Innovalab with IMT Cusco"
  twitter-card: 
    image: "https://raw.githubusercontent.com/healthinnovation/Harmonize-Project/main/img/twitter-card.png"
    creator: "@antony_barja"
    site: "@antony_barja"
  open-graph:
    description: "Harmonize is a collaboration project with Colombia, Brazil, Dominican Republic and Peru, led by the Barcelona Supercomputing Center and funded by Wellcome Trust, that aims to develop a digital infrastructure to harmonize climate, health and drone data for every country in the consortium."
    image: "https://raw.githubusercontent.com/healthinnovation/Harmonize-Project/main/img/twitter-card.png"
  navbar:
    logo: https://epi-rgee.netlify.app/logos/logo_v2.png
    left:
      - href: index.qmd
        text: Home
      - href: webmap.qmd
        text: Webmap

    right:
      - icon: github
        href: https://github.com/healthinnovation/harmonize
      - icon: twitter
        href: https://twitter.com/innovalab_imt
  
format:
  html:
    theme: cosmo
    css: css/style.css
    toc: true

editor: visual